/**
 * SHAP Explanation card — displayed on the UserProfile page.
 * Shows the natural-language explanation in a highlighted panel.
 */
export default function SHAPExplanation({ explanation, isHighRisk = false }) {
  if (!explanation) return null;

  return (
    <div
      id="shap-explanation-card"
      className={`rounded-xl border p-5 animate-fade-in ${
        isHighRisk
          ? "bg-high/5 border-high/30 glow-red"
          : "bg-medium/5 border-medium/30 glow-yellow"
      }`}
    >
      {/* Header */}
      <div className="flex items-center gap-2 mb-3">
        <div
          className={`w-7 h-7 rounded-lg flex items-center justify-center text-sm flex-shrink-0 ${
            isHighRisk ? "bg-high/20 text-high" : "bg-medium/20 text-medium"
          }`}
        >
          <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5">
            <circle cx="12" cy="12" r="10" />
            <line x1="12" y1="8" x2="12" y2="12" />
            <line x1="12" y1="16" x2="12.01" y2="16" />
          </svg>
        </div>
        <div>
          <h4 className={`text-sm font-bold ${isHighRisk ? "text-high" : "text-medium"}`}>
            AI Threat Explanation
          </h4>
          <p className="text-[10px] text-muted uppercase tracking-widest">SHAP-Based Anomaly Analysis</p>
        </div>
      </div>

      {/* Explanation text */}
      <p className="text-sm text-slate-300 leading-relaxed pl-9">
        {explanation}
      </p>

      {/* Footer */}
      <div className="flex items-center gap-2 mt-3 pl-9">
        <div className={`w-1.5 h-1.5 rounded-full ${isHighRisk ? "bg-high" : "bg-medium"} animate-pulse`} />
        <span className="text-[10px] text-muted font-mono uppercase tracking-wide">
          Generated by SHAP TreeExplainer · Isolation Forest
        </span>
      </div>
    </div>
  );
}
